//! Generates flash-resident static tables from vendored Gen 1 JSON.
//!
//! Reads:
//!   data/gen1_mons.json
//!   data/gen1_moves.json
//!   data/type-chart.json
//!
//! Emits OUT_DIR/gen1_tables.rs with:
//!   pub static SPECIES: &[SpeciesEntry; N];
//!   pub static MOVES:   &[MoveEntry;    N];
//!   pub const  TYPE_COUNT: usize = 18;
//!   pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT];

use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let mons_path = manifest_dir.join("data/gen1_mons.json");
    let moves_path = manifest_dir.join("data/gen1_moves.json");
    let typechart_path = manifest_dir.join("data/type-chart.json");

    println!("cargo:rerun-if-changed=data/gen1_mons.json");
    println!("cargo:rerun-if-changed=data/gen1_moves.json");
    println!("cargo:rerun-if-changed=data/type-chart.json");
    println!("cargo:rerun-if-changed=build.rs");

    let mons: BTreeMap<String, Value> = serde_json::from_str(
        &fs::read_to_string(&mons_path).expect("read mons"),
    )
    .expect("parse mons");

    let moves: BTreeMap<String, Value> = serde_json::from_str(
        &fs::read_to_string(&moves_path).expect("read moves"),
    )
    .expect("parse moves");

    let typechart: Value = serde_json::from_str(
        &fs::read_to_string(&typechart_path).expect("read type chart"),
    )
    .expect("parse type chart");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("gen1_tables.rs");

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    emit_species(&mons, &mut out);
    out.push('\n');
    emit_moves(&moves, &mut out);
    out.push('\n');
    emit_type_chart(&typechart, &mut out);

    fs::write(&dest, out).expect("write gen1_tables.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
// Species
// ─────────────────────────────────────────────────────────────────────────────

fn emit_species(mons: &BTreeMap<String, Value>, out: &mut String) {
    // Filter: keep entries where `base_species == name` (excludes formes/megas
    // that point at a base). This gives ~151 Gen 1 originals.
    let mut filtered: Vec<(&String, &Value)> = mons
        .iter()
        .filter(|(_, v)| {
            let name = v.get("name").and_then(|x| x.as_str()).unwrap_or("");
            let base = v.get("base_species").and_then(|x| x.as_str()).unwrap_or("");
            name == base
        })
        .collect();
    filtered.sort_by(|(a, _), (b, _)| a.cmp(b));

    out.push_str(&format!("pub static SPECIES: [SpeciesEntry; {}] = [\n", filtered.len()));
    for (id, v) in &filtered {
        let name = v.get("name").and_then(|x| x.as_str()).unwrap_or(id);
        let prim = v.get("primary_type").and_then(|x| x.as_str()).unwrap_or("Normal");
        let sec = v
            .get("secondary_type")
            .and_then(|x| x.as_str())
            .unwrap_or("None");
        let stats = v.get("base_stats").cloned().unwrap_or(Value::Null);
        let hp = stat_u16(&stats, "hp");
        let atk = stat_u16(&stats, "atk");
        let def = stat_u16(&stats, "def");
        // Gen 1: spc = the higher of spa/spd; the source data has both, but
        // game-mechanically only "Special" matters. Use spa (Special Attack)
        // since RBY base_stats split was: physical/special-attack/-defense all
        // share one Special stat. Most modern data files use spa to mean
        // "Special" for Gen 1 records.
        let spc = stat_u16(&stats, "spa");
        let spe = stat_u16(&stats, "spe");
        let catch_rate = v.get("catch_rate").and_then(|x| x.as_u64()).unwrap_or(0) as u8;
        let base_exp = v.get("base_exp_yield").and_then(|x| x.as_u64()).unwrap_or(0) as u16;
        out.push_str(&format!(
            "    SpeciesEntry {{ id: \"{}\", name: \"{}\", primary_type: Type::{}, secondary_type: Type::{}, base_stats: [{}, {}, {}, {}, {}], catch_rate: {}, base_exp_yield: {} }},\n",
            id, name, prim, sec, hp, atk, def, spc, spe, catch_rate, base_exp,
        ));
    }
    out.push_str("];\n");
}

fn stat_u16(stats: &Value, key: &str) -> u16 {
    stats.get(key).and_then(|x| x.as_u64()).unwrap_or(0) as u16
}

// ─────────────────────────────────────────────────────────────────────────────
// Moves
// ─────────────────────────────────────────────────────────────────────────────

fn emit_moves(moves: &BTreeMap<String, Value>, out: &mut String) {
    let mut entries: Vec<(&String, &Value)> = moves.iter().collect();
    entries.sort_by(|(a, _), (b, _)| a.cmp(b));

    out.push_str(&format!("pub static MOVES: [MoveEntry; {}] = [\n", entries.len()));
    for (id, v) in &entries {
        let name = v.get("name").and_then(|x| x.as_str()).unwrap_or(id);
        let mtype = v.get("primary_type").and_then(|x| x.as_str()).unwrap_or("Normal");
        let category = v.get("category").and_then(|x| x.as_str()).unwrap_or("Status");
        let category_variant = match category {
            "Physical" => "Physical",
            "Special" => "Special",
            _ => "Status",
        };
        let power = v.get("base_power").and_then(|x| x.as_u64()).unwrap_or(0) as u8;
        let accuracy = v
            .get("accuracy")
            .and_then(|x| x.as_u64())
            .unwrap_or(0) as u8;
        let pp = v.get("pp").and_then(|x| x.as_u64()).unwrap_or(0) as u8;

        let (effect_kind, p0, p1) = classify_move(id, v);
        let mut flags = 0u8;
        if v.get("crit_ratio").and_then(|x| x.as_u64()).unwrap_or(1) >= 2 {
            flags |= 0x01; // FLAG_HIGH_CRIT
        }
        if let Some(arr) = v.get("flags").and_then(|x| x.as_array()) {
            for f in arr {
                if let Some(s) = f.as_str() {
                    if s == "Contact" {
                        flags |= 0x02;
                    }
                }
            }
        }
        // Priority: Quick Attack +1, Counter -1 (Gen 1).
        if id.as_str() == "quickattack" || id.as_str() == "extremespeed" {
            flags |= 0x08;
        }
        if id.as_str() == "counter" {
            flags |= 0x10;
        }

        out.push_str(&format!(
            "    MoveEntry {{ id: \"{}\", name: \"{}\", move_type: Type::{}, category: MoveCategory::{}, power: {}, accuracy: {}, pp: {}, effect_kind: MoveEffectKind::{}, effect_param0: {}, effect_param1: {}, flags: 0x{:02x} }},\n",
            id, name, mtype, category_variant, power, accuracy, pp, effect_kind, p0, p1, flags,
        ));
    }
    out.push_str("];\n");
}

/// Map move id → (effect_kind, param0, param1).
///
/// param0/param1 meaning is documented per-variant in tables.rs.
///
/// Stat encoding for boost params: Atk=1, Def=2, SpAtk=3, SpDef=4, Spe=5.
/// Status encoding: PSN=1, BRN=2, FRZ=3, PAR=4, SLP=5, CONFUSED=6, BAD_PSN=7.
fn classify_move(id: &str, v: &Value) -> (&'static str, u8, u8) {
    // Multi-hit comes from JSON directly.
    if let Some(arr) = v.get("multihit").and_then(|x| x.as_array()) {
        if arr.len() == 2 {
            return ("MultiHit2to5", 0, 0);
        } else if arr.len() == 1 {
            let n = arr[0].as_u64().unwrap_or(2) as u8;
            return ("MultiHitFixed", n, 0);
        }
    }

    // Hand-curated Gen 1 effect map. ~165 moves; default = Damage / NoOp.
    match id {
        // ── Damage + status (chance/100 encoded as chance*255/100) ───────────
        "thunder" | "thunderbolt" | "thundershock" | "bodyslam" => ("DamageMaybeStatus", 4, 76), // PAR 30%
        "fireblast" => ("DamageMaybeStatus", 2, 76), // BRN 30%
        "flamethrower" | "ember" | "firepunch" => ("DamageMaybeStatus", 2, 25), // BRN 10%
        "icebeam" | "blizzard" | "icepunch" => ("DamageMaybeStatus", 3, 25), // FRZ 10%
        "poisonsting" | "sludge" | "smog" => ("DamageMaybeStatus", 1, 51), // PSN 20%
        "lick" => ("DamageMaybeStatus", 4, 76), // PAR 30%
        "thunderpunch" => ("DamageMaybeStatus", 4, 25), // PAR 10%
        "psybeam" | "confusion" => ("DamageMaybeStatus", 6, 25), // CONFUSED 10%

        // ── Damage + flinch ──────────────────────────────────────────────────
        "bite" | "stomp" | "rollingkick" | "headbutt" | "lowkick" => ("DamageMaybeFlinch", 76, 0),
        "hyperfang" => ("DamageMaybeFlinch", 25, 0),

        // ── Damage + boost ───────────────────────────────────────────────────
        "acid" => ("DamageMaybeBoostTarget", 2, 0xFF & ((-1i8) as u8)), // def -1 33%; encoded via param2; simplified
        "aurorabeam" => ("DamageMaybeBoostTarget", 1, 0xFF & ((-1i8) as u8)),

        // ── Pure status ──────────────────────────────────────────────────────
        "thunderwave" | "stunspore" | "glare" => ("StatusOnly", 4, 0),
        "sleeppowder" | "spore" | "hypnosis" | "lovelykiss" | "sing" => ("StatusOnly", 5, 0),
        "poisonpowder" | "poisongas" => ("StatusOnly", 1, 0),
        "willowisp" => ("StatusOnly", 2, 0),
        "toxic" => ("StatusOnly", 7, 0),
        "confuseray" | "supersonic" => ("StatusOnly", 6, 0),

        // ── Stat boosts: self ────────────────────────────────────────────────
        "swordsdance" => ("BoostSelf", 1, 2),
        "meditate" | "sharpen" => ("BoostSelf", 1, 1),
        "harden" | "withdraw" => ("BoostSelf", 2, 1),
        "defensecurl" => ("BoostSelf", 2, 1),
        "barrier" | "acidarmor" => ("BoostSelf", 2, 2),
        "agility" => ("BoostSelf", 5, 2),
        "amnesia" => ("BoostSelf", 3, 2),
        "growth" => ("BoostSelf", 3, 1),

        // ── Stat boosts: target ──────────────────────────────────────────────
        "growl" => ("BoostTarget", 1, 0xFF & ((-1i8) as u8)),
        "tailwhip" | "leer" => ("BoostTarget", 2, 0xFF & ((-1i8) as u8)),
        "stringshot" | "cottonspore" => ("BoostTarget", 5, 0xFF & ((-1i8) as u8)),
        "screech" => ("BoostTarget", 2, 0xFF & ((-2i8) as u8)),
        "sandattack" | "smokescreen" | "flash" | "kinesis" => ("BoostTarget", 6 /*acc*/, 0xFF & ((-1i8) as u8)),

        // ── Drain ────────────────────────────────────────────────────────────
        "absorb" | "megadrain" | "leechlife" => ("DrainHp", 1, 2),

        // ── Recoil ───────────────────────────────────────────────────────────
        "takedown" | "doubleedge" | "submission" => ("Recoil1of4", 0, 0),

        // ── Crash on miss ────────────────────────────────────────────────────
        "hijumpkick" | "jumpkick" => ("CrashOnMiss", 0, 0),

        // ── OHKO ─────────────────────────────────────────────────────────────
        "fissure" | "horndrill" | "guillotine" => ("Ohko", 0, 0),

        // ── Force switch ─────────────────────────────────────────────────────
        "whirlwind" | "roar" => ("ForceSwitchTarget", 0, 0),

        // ── Fixed/level damage ───────────────────────────────────────────────
        "seismictoss" | "nightshade" => ("LevelDamage", 0, 0),
        "sonicboom" => ("FlatDamage", 20, 0),
        "dragonrage" => ("FlatDamage", 40, 0),
        "psywave" => ("Psywave", 0, 0),
        "superfang" => ("HalfHp", 0, 0),

        // ── Healing ──────────────────────────────────────────────────────────
        "recover" | "softboiled" => ("HealHalf", 0, 0),
        "rest" => ("Rest", 0, 0),

        // ── Two-turn moves ───────────────────────────────────────────────────
        "solarbeam" | "skullbash" | "skyattack" | "razorwind" => ("TwoTurn", 0, 0),
        "fly" | "dig" => ("TwoTurn", 1, 0), // invulnerable phase

        // ── Special-cased ────────────────────────────────────────────────────
        "bide" => ("Bide", 0, 0),
        "hyperbeam" => ("HyperBeam", 0, 0),
        "counter" => ("Counter", 0, 0),
        "mirrormove" => ("MirrorMove", 0, 0),
        "mimic" => ("Mimic", 0, 0),
        "transform" => ("Transform", 0, 0),
        "substitute" => ("Substitute", 0, 0),
        "disable" => ("Disable", 0, 0),
        "wrap" | "bind" | "firespin" | "clamp" => ("Wrap", 0, 0),
        "leechseed" => ("LeechSeed", 0, 0),
        "lightscreen" => ("LightScreen", 0, 0),
        "reflect" => ("Reflect", 0, 0),
        "mist" => ("Mist", 0, 0),
        "focusenergy" => ("FocusEnergy", 0, 0),
        "conversion" => ("Conversion", 0, 0),
        "haze" => ("Haze", 0, 0),
        "metronome" => ("Metronome", 0, 0),
        "payday" => ("PayDay", 0, 0),
        "selfdestruct" | "explosion" => ("SelfDestruct", 0, 0),

        // ── No-ops ───────────────────────────────────────────────────────────
        "splash" => ("NoOp", 0, 0),

        // ── Default: plain damage if it has power, else NoOp ─────────────────
        _ => {
            let power = v.get("base_power").and_then(|x| x.as_u64()).unwrap_or(0);
            if power > 0 {
                ("Damage", 0, 0)
            } else {
                ("NoOp", 0, 0)
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Type chart
// ─────────────────────────────────────────────────────────────────────────────

const TYPE_NAMES: &[&str] = &[
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison",
    "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
];

fn emit_type_chart(typechart: &Value, out: &mut String) {
    let n = TYPE_NAMES.len();
    out.push_str(&format!("pub const TYPE_COUNT: usize = {};\n", n));
    out.push_str(&format!(
        "pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT] = [\n"
    ));

    let types = typechart
        .get("types")
        .and_then(|x| x.as_object())
        .expect("type chart 'types' key");

    for atk in TYPE_NAMES {
        out.push_str("    [");
        for def in TYPE_NAMES {
            let mult = types
                .get(*atk)
                .and_then(|m| m.get(*def))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0);
            // ×10: 0=immune, 5=½, 10=1×, 20=2×.
            let e = (mult * 10.0) as u8;
            out.push_str(&format!("{}, ", e));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");
}
