//! Generates flash-resident static tables from vendored Gen 1 JSON.
//!
//! Reads:
//!   data/rby_moves.json    — cartridge move table (converted from pret/pokered
//!                            data/moves/moves.asm; effect names are pokered's)
//!   data/rby_species.json  — RBY base stats + Gen 1 typing (converted from
//!                            Pokémon Showdown data/mods/gen1/pokedex.ts)
//!   data/gen1_mons.json    — modern species data (names, catch rate, exp)
//!   data/type-chart.json   — modern chart, patched to Gen 1 below
//!
//! Emits OUT_DIR/gen1_tables.rs with:
//!   pub static SPECIES: [SpeciesEntry; N];
//!   pub static MOVES:   [MoveEntry;    N];
//!   pub const  TYPE_COUNT: usize = 18;
//!   pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT];

use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let mons_path = manifest_dir.join("data/gen1_mons.json");
    let rby_moves_path = manifest_dir.join("data/rby_moves.json");
    let rby_species_path = manifest_dir.join("data/rby_species.json");
    let typechart_path = manifest_dir.join("data/type-chart.json");

    println!("cargo:rerun-if-changed=data/gen1_mons.json");
    println!("cargo:rerun-if-changed=data/rby_moves.json");
    println!("cargo:rerun-if-changed=data/rby_species.json");
    println!("cargo:rerun-if-changed=data/type-chart.json");
    println!("cargo:rerun-if-changed=build.rs");

    let mons: BTreeMap<String, Value> = serde_json::from_str(
        &fs::read_to_string(&mons_path).expect("read mons"),
    )
    .expect("parse mons");

    let rby_moves: BTreeMap<String, Value> = serde_json::from_str(
        &fs::read_to_string(&rby_moves_path).expect("read rby moves"),
    )
    .expect("parse rby moves");

    let rby_species: BTreeMap<String, Value> = serde_json::from_str(
        &fs::read_to_string(&rby_species_path).expect("read rby species"),
    )
    .expect("parse rby species");

    let typechart: Value = serde_json::from_str(
        &fs::read_to_string(&typechart_path).expect("read type chart"),
    )
    .expect("parse type chart");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("gen1_tables.rs");

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    emit_species(&mons, &rby_species, &mut out);
    out.push('\n');
    emit_moves(&rby_moves, &mut out);
    out.push('\n');
    emit_type_chart(&typechart, &mut out);

    fs::write(&dest, out).expect("write gen1_tables.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
// Species
// ─────────────────────────────────────────────────────────────────────────────

fn emit_species(mons: &BTreeMap<String, Value>, rby: &BTreeMap<String, Value>, out: &mut String) {
    // rby_species.json holds exactly the 151 Gen 1 species with cartridge base
    // stats (single Special) and Gen 1 typing (no Steel/Fairy retcons).
    out.push_str(&format!("pub static SPECIES: [SpeciesEntry; {}] = [\n", rby.len()));
    for (id, r) in rby {
        let v = mons.get(id).cloned().unwrap_or(Value::Null);
        let name = v.get("name").and_then(|x| x.as_str()).unwrap_or(id);
        let prim = r.get("primary_type").and_then(|x| x.as_str()).unwrap_or("Normal");
        let sec = r.get("secondary_type").and_then(|x| x.as_str()).unwrap_or("None");
        let stats = r.get("base_stats").cloned().unwrap_or(Value::Null);
        let hp = stat_u16(&stats, "hp");
        let atk = stat_u16(&stats, "atk");
        let def = stat_u16(&stats, "def");
        let spc = stat_u16(&stats, "spc");
        let spe = stat_u16(&stats, "spe");
        let catch_rate = v.get("catch_rate").and_then(|x| x.as_u64()).unwrap_or(0) as u8;
        let base_exp = v.get("base_exp_yield").and_then(|x| x.as_u64()).unwrap_or(0) as u16;
        out.push_str(&format!(
            "    SpeciesEntry {{ id: \"{}\", name: \"{}\", primary_type: Type::{}, secondary_type: Type::{}, base_stats: [{}, {}, {}, {}, {}], catch_rate: {}, base_exp_yield: {} }},\n",
            id, name, prim, sec, hp, atk, def, spc, spe, catch_rate, base_exp,
        ));
    }
    out.push_str("];\n");
}

fn stat_u16(stats: &Value, key: &str) -> u16 {
    stats.get(key).and_then(|x| x.as_u64()).unwrap_or(0) as u16
}

// ─────────────────────────────────────────────────────────────────────────────
// Moves
// ─────────────────────────────────────────────────────────────────────────────

/// Gen 1 damage category is determined by the move's TYPE, not per-move.
fn category_for(mtype: &str, power: u64, effect: &str) -> &'static str {
    let damaging = power > 0
        || matches!(effect, "SPECIAL_DAMAGE_EFFECT" | "SUPER_FANG_EFFECT" | "OHKO_EFFECT");
    if !damaging {
        return "Status";
    }
    match mtype {
        "Fire" | "Water" | "Grass" | "Electric" | "Psychic" | "Ice" | "Dragon" => "Special",
        _ => "Physical",
    }
}

fn emit_moves(moves: &BTreeMap<String, Value>, out: &mut String) {
    out.push_str(&format!("pub static MOVES: [MoveEntry; {}] = [\n", moves.len()));
    for (id, v) in moves {
        let name = v.get("name").and_then(|x| x.as_str()).unwrap_or(id);
        let mtype = v.get("type").and_then(|x| x.as_str()).unwrap_or("Normal");
        let power = v.get("power").and_then(|x| x.as_u64()).unwrap_or(0);
        let accuracy = v.get("accuracy").and_then(|x| x.as_u64()).unwrap_or(0) as u8;
        let pp = v.get("pp").and_then(|x| x.as_u64()).unwrap_or(0) as u8;
        let effect = v.get("effect").and_then(|x| x.as_str()).unwrap_or("NO_ADDITIONAL_EFFECT");

        let category = category_for(mtype, power, effect);
        let (effect_kind, p0, p1) = classify_move(id, effect);

        let mut flags = 0u8;
        // Gen 1 high-crit set (8× base crit chance).
        if matches!(id.as_str(), "crabhammer" | "karatechop" | "razorleaf" | "slash") {
            flags |= 0x01; // FLAG_HIGH_CRIT
        }
        // Priority brackets: Quick Attack +1, Counter -1; everything else 0.
        if id == "quickattack" {
            flags |= 0x08; // FLAG_PRIO_PLUS
        }
        if id == "counter" {
            flags |= 0x10; // FLAG_PRIO_MINUS
        }
        // Damaging moves that ignore type immunity in Gen 1 (fixed damage and
        // partial-trapping; status moves ignore immunity unconditionally).
        if matches!(effect, "SPECIAL_DAMAGE_EFFECT" | "SUPER_FANG_EFFECT" | "TRAPPING_EFFECT")
            && id != "dragonrage"
            && id != "psywave"
        {
            flags |= 0x20; // FLAG_IGNORE_IMMUNITY
        }
        // Swift and Transform hit through Fly/Dig semi-invulnerability.
        if id == "swift" || id == "transform" {
            flags |= 0x40; // FLAG_HITS_INVULN
        }

        // The damage formula clamps power to u8; Gen 1 max is Explosion at 170.
        let power = power.min(255) as u8;

        out.push_str(&format!(
            "    MoveEntry {{ id: \"{}\", name: \"{}\", move_type: Type::{}, category: MoveCategory::{}, power: {}, accuracy: {}, pp: {}, effect_kind: MoveEffectKind::{}, effect_param0: {}, effect_param1: {}, flags: 0x{:02x} }},\n",
            id, name, mtype, category, power, accuracy, pp, effect_kind, p0, p1, flags,
        ));
    }
    out.push_str("];\n");
}

/// Map pokered effect constant (+ id special cases) → (MoveEffectKind, p0, p1).
///
/// Stat encoding for boost params: Atk=1, Def=2, Spc=3, Spe=5, Acc=6, Eva=7.
/// Status encoding: PSN=1, BRN=2, FRZ=3, PAR=4, SLP=5, CONFUSED=6, BAD_PSN=7.
/// Secondary chances are /256 thresholds straight from the cartridge:
///   SIDE_EFFECT1 = 26, SIDE_EFFECT2 = 77, poison 52/103, stat-down 85,
///   confusion 25.
fn classify_move(id: &str, effect: &str) -> (&'static str, u8, u8) {
    // Id-level special cases first.
    match id {
        // pokered's table lists Counter as NO_ADDITIONAL_EFFECT; its logic is
        // special-cased by move id in the cartridge engine.
        "counter" => return ("Counter", 0, 0),
        "toxic" => return ("StatusOnly", 7, 0),
        "rest" => return ("Rest", 0, 0),
        "struggle" => return ("StruggleRecoil", 0, 0),
        "sonicboom" => return ("FlatDamage", 20, 0),
        "dragonrage" => return ("FlatDamage", 40, 0),
        "seismictoss" | "nightshade" => return ("LevelDamage", 0, 0),
        "psywave" => return ("Psywave", 0, 0),
        "fly" | "dig" => return ("TwoTurn", 1, 0), // invulnerable while charging
        _ => {}
    }

    match effect {
        "NO_ADDITIONAL_EFFECT" | "PAY_DAY_EFFECT" | "SWIFT_EFFECT" => ("Damage", 0, 0),

        // ── Damage + status side effects ─────────────────────────────────────
        "POISON_SIDE_EFFECT1" => ("DamageMaybeStatus", 1, 52),
        "POISON_SIDE_EFFECT2" => ("DamageMaybeStatus", 1, 103),
        "BURN_SIDE_EFFECT1" => ("DamageMaybeStatus", 2, 26),
        "BURN_SIDE_EFFECT2" => ("DamageMaybeStatus", 2, 77),
        "FREEZE_SIDE_EFFECT1" => ("DamageMaybeStatus", 3, 26),
        "PARALYZE_SIDE_EFFECT1" => ("DamageMaybeStatus", 4, 26),
        "PARALYZE_SIDE_EFFECT2" => ("DamageMaybeStatus", 4, 77),
        "CONFUSION_SIDE_EFFECT" => ("DamageMaybeStatus", 6, 25),
        "FLINCH_SIDE_EFFECT1" => ("DamageMaybeFlinch", 26, 0),
        "FLINCH_SIDE_EFFECT2" => ("DamageMaybeFlinch", 77, 0),

        // ── Damage + 85/256 stat drop ────────────────────────────────────────
        "ATTACK_DOWN_SIDE_EFFECT" => ("DamageMaybeBoostTarget", 1, neg(1)),
        "DEFENSE_DOWN_SIDE_EFFECT" => ("DamageMaybeBoostTarget", 2, neg(1)),
        "SPECIAL_DOWN_SIDE_EFFECT" => ("DamageMaybeBoostTarget", 3, neg(1)),
        "SPEED_DOWN_SIDE_EFFECT" => ("DamageMaybeBoostTarget", 5, neg(1)),

        // ── Pure status ──────────────────────────────────────────────────────
        "POISON_EFFECT" => ("StatusOnly", 1, 0),
        "PARALYZE_EFFECT" => ("StatusOnly", 4, 0),
        "SLEEP_EFFECT" => ("StatusOnly", 5, 0),
        "CONFUSION_EFFECT" => ("StatusOnly", 6, 0),

        // ── Stat stages ──────────────────────────────────────────────────────
        "ATTACK_UP1_EFFECT" => ("BoostSelf", 1, 1),
        "ATTACK_UP2_EFFECT" => ("BoostSelf", 1, 2),
        "DEFENSE_UP1_EFFECT" => ("BoostSelf", 2, 1),
        "DEFENSE_UP2_EFFECT" => ("BoostSelf", 2, 2),
        "SPECIAL_UP1_EFFECT" => ("BoostSelf", 3, 1),
        "SPECIAL_UP2_EFFECT" => ("BoostSelf", 3, 2),
        "SPEED_UP2_EFFECT" => ("BoostSelf", 5, 2),
        "EVASION_UP1_EFFECT" => ("BoostSelf", 7, 1),
        "ATTACK_DOWN1_EFFECT" => ("BoostTarget", 1, neg(1)),
        "DEFENSE_DOWN1_EFFECT" => ("BoostTarget", 2, neg(1)),
        "DEFENSE_DOWN2_EFFECT" => ("BoostTarget", 2, neg(2)),
        "SPEED_DOWN1_EFFECT" => ("BoostTarget", 5, neg(1)),
        "ACCURACY_DOWN1_EFFECT" => ("BoostTarget", 6, neg(1)),

        // ── Multi-hit ────────────────────────────────────────────────────────
        "TWO_TO_FIVE_ATTACKS_EFFECT" => ("MultiHit2to5", 0, 0),
        "ATTACK_TWICE_EFFECT" => ("MultiHitFixed", 2, 0),
        "TWINEEDLE_EFFECT" => ("Twineedle", 2, 52), // 2 hits, 20% psn

        // ── Drain / recoil / crash ───────────────────────────────────────────
        "DRAIN_HP_EFFECT" => ("DrainHp", 1, 2),
        "DREAM_EATER_EFFECT" => ("DreamEater", 1, 2),
        "RECOIL_EFFECT" => ("Recoil1of4", 0, 0),
        "JUMP_KICK_EFFECT" => ("CrashOnMiss", 0, 0),

        // ── Everything else ──────────────────────────────────────────────────
        "OHKO_EFFECT" => ("Ohko", 0, 0),
        "SWITCH_AND_TELEPORT_EFFECT" => ("ForceSwitchTarget", 0, 0),
        "SUPER_FANG_EFFECT" => ("HalfHp", 0, 0),
        "HEAL_EFFECT" => ("HealHalf", 0, 0),
        "CHARGE_EFFECT" => ("TwoTurn", 0, 0),
        "FLY_EFFECT" => ("TwoTurn", 1, 0),
        "BIDE_EFFECT" => ("Bide", 0, 0),
        "THRASH_PETAL_DANCE_EFFECT" => ("ThrashLock", 0, 0),
        "RAGE_EFFECT" => ("Rage", 0, 0),
        "HYPER_BEAM_EFFECT" => ("HyperBeam", 0, 0),
        "COUNTER_EFFECT" => ("Counter", 0, 0),
        "MIRROR_MOVE_EFFECT" => ("MirrorMove", 0, 0),
        "MIMIC_EFFECT" => ("Mimic", 0, 0),
        "TRANSFORM_EFFECT" => ("Transform", 0, 0),
        "SUBSTITUTE_EFFECT" => ("Substitute", 0, 0),
        "DISABLE_EFFECT" => ("Disable", 0, 0),
        "TRAPPING_EFFECT" => ("Wrap", 0, 0),
        "LEECH_SEED_EFFECT" => ("LeechSeed", 0, 0),
        "LIGHT_SCREEN_EFFECT" => ("LightScreen", 0, 0),
        "REFLECT_EFFECT" => ("Reflect", 0, 0),
        "MIST_EFFECT" => ("Mist", 0, 0),
        "FOCUS_ENERGY_EFFECT" => ("FocusEnergy", 0, 0),
        "CONVERSION_EFFECT" => ("Conversion", 0, 0),
        "HAZE_EFFECT" => ("Haze", 0, 0),
        "METRONOME_EFFECT" => ("Metronome", 0, 0),
        "EXPLODE_EFFECT" => ("SelfDestruct", 0, 0),
        "SPLASH_EFFECT" => ("NoOp", 0, 0),

        other => panic!("unmapped RBY effect for {id}: {other}"),
    }
}

fn neg(n: i8) -> u8 {
    (-n) as i8 as u8
}

// ─────────────────────────────────────────────────────────────────────────────
// Type chart
// ─────────────────────────────────────────────────────────────────────────────

const TYPE_NAMES: &[&str] = &[
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison",
    "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
];

/// Gen 1 chart differences vs the modern chart (attacker, defender, ×10 mult):
///   Ghost → Psychic  0  (the famous bug: intended 2×, shipped as immune)
///   Bug   → Poison  20  (modern ½×)
///   Poison→ Bug     20  (modern 1×)
///   Ice   → Fire    10  (modern ½×)
/// Dark/Steel/Fairy don't exist in Gen 1; their rows/columns are unreachable
/// because no RBY species or move carries those types.
const GEN1_PATCHES: &[(&str, &str, u8)] = &[
    ("Ghost", "Psychic", 0),
    ("Bug", "Poison", 20),
    ("Poison", "Bug", 20),
    ("Ice", "Fire", 10),
];

fn emit_type_chart(typechart: &Value, out: &mut String) {
    let n = TYPE_NAMES.len();
    out.push_str(&format!("pub const TYPE_COUNT: usize = {};\n", n));
    out.push_str(&format!(
        "pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT] = [\n"
    ));

    let types = typechart
        .get("types")
        .and_then(|x| x.as_object())
        .expect("type chart 'types' key");

    for atk in TYPE_NAMES {
        out.push_str("    [");
        for def in TYPE_NAMES {
            let mut e = types
                .get(*atk)
                .and_then(|m| m.get(*def))
                .and_then(|v| v.as_f64())
                .map(|mult| (mult * 10.0) as u8)
                .unwrap_or(10);
            for (a, d, patched) in GEN1_PATCHES {
                if a == atk && d == def {
                    e = *patched;
                }
            }
            out.push_str(&format!("{}, ", e));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");
}
