extern crate alloc;

use alloc::vec::Vec;

use anyhow::Result;
use battler_data::{
    AbilityData,
    ClauseData,
    ConditionData,
    DataStore,
    Id,
    ItemData,
    MoveData,
    SpeciesData,
    Type,
    TypeChart,
    TypeTable,
};

// Generated by build.rs from battler/battle-data/data.
// Contains: TYPE_CHART, ALIASES, ABILITIES, CONDITIONS, SPECIES, MOVES.
// All tables are sorted by key; values are CBOR-encoded binary.
include!(concat!(env!("OUT_DIR"), "/battle_data.rs"));

// ── lookup helpers ────────────────────────────────────────────────────────────

fn find(table: &[(&'static str, &'static [u8])], id: &Id) -> Option<&'static [u8]> {
    let key: &str = id.as_ref();
    table.binary_search_by(|(k, _)| (*k).cmp(key))
        .ok()
        .map(|i| table[i].1)
}

fn parse<T: serde::de::DeserializeOwned>(bytes: &[u8]) -> Result<T> {
    ciborium::de::from_reader(bytes).map_err(|e| anyhow::anyhow!("{e}"))
}

// ── data store ────────────────────────────────────────────────────────────────

pub struct FlashDataStore {
    type_chart: TypeChart,
}

impl FlashDataStore {
    pub fn new() -> Self {
        // build.rs emits one CBOR-encoded entry; value is the inner TypeTable object only.
        let types_bytes = TYPE_CHART
            .iter()
            .find(|(k, _)| *k == "types")
            .map(|(_, b)| *b)
            .expect("type chart must include `types`");
        let types: TypeTable<Type> = parse(types_bytes).expect("type chart parse");
        let type_chart = TypeChart::from_filled(types);
        Self { type_chart }
    }
}

unsafe impl Send for FlashDataStore {}
unsafe impl Sync for FlashDataStore {}

impl DataStore for FlashDataStore {
    fn all_move_ids(&self, filter: &dyn Fn(&MoveData) -> bool) -> Result<Vec<Id>> {
        let mut ids = Vec::new();
        for (key, bytes) in MOVES {
            if let Ok(data) = parse::<MoveData>(bytes) {
                if filter(&data) {
                    ids.push(Id::from(*key));
                }
            }
        }
        Ok(ids)
    }

    fn get_type_chart(&self) -> Result<TypeChart> {
        Ok(self.type_chart.clone())
    }

    fn translate_alias(&self, id: &Id) -> Result<Option<Id>> {
        Ok(find(ALIASES, id).and_then(|b| parse::<Id>(b).ok()))
    }

    fn get_ability(&self, id: &Id) -> Result<Option<AbilityData>> {
        match find(ABILITIES, id) {
            Some(b) => Ok(Some(parse(b)?)),
            None => Ok(None),
        }
    }

    fn get_clause(&self, _id: &Id) -> Result<Option<ClauseData>> {
        Ok(None)
    }

    fn get_condition(&self, id: &Id) -> Result<Option<ConditionData>> {
        match find(CONDITIONS, id) {
            Some(b) => Ok(Some(parse(b)?)),
            None => Ok(None),
        }
    }

    fn get_item(&self, _id: &Id) -> Result<Option<ItemData>> {
        Ok(None)
    }

    fn get_move(&self, id: &Id) -> Result<Option<MoveData>> {
        match find(MOVES, id) {
            Some(b) => Ok(Some(parse(b)?)),
            None => Ok(None),
        }
    }

    fn get_species(&self, id: &Id) -> Result<Option<SpeciesData>> {
        match find(SPECIES, id) {
            Some(b) => Ok(Some(parse(b)?)),
            None => Ok(None),
        }
    }
}
