extern crate alloc;

use alloc::vec::Vec;

use anyhow::Result;
use battler_data::{
    AbilityData,
    ClauseData,
    ConditionData,
    DataStore,
    Id,
    ItemData,
    MoveData,
    SpeciesData,
    TypeChart,
};

// Generated by build.rs from battler/battle-data/data.
// Contains: TYPE_CHART, ALIASES, CONDITIONS, SPECIES, MOVES.
include!(concat!(env!("OUT_DIR"), "/battle_data.rs"));

// ── lookup helpers ────────────────────────────────────────────────────────────

fn find(table: &[(&'static str, &'static str)], id: &Id) -> Option<&'static str> {
    let key: &str = id.as_ref();
    // Linear scan is fine — battler's Dex caches after first hit.
    table.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}

fn parse<T: serde::de::DeserializeOwned>(json: &str) -> Result<T> {
    serde_json::from_str(json).map_err(|e| anyhow::anyhow!("{e}"))
}

// ── data store ────────────────────────────────────────────────────────────────

pub struct FlashDataStore {
    type_chart: TypeChart,
}

impl FlashDataStore {
    pub fn new() -> Self {
        // TYPE_CHART is a single-entry table with key "".
        let tc_json = TYPE_CHART[0].1;
        let type_chart: TypeChart = parse(tc_json).expect("type chart parse");
        Self { type_chart }
    }
}

unsafe impl Send for FlashDataStore {}
unsafe impl Sync for FlashDataStore {}

impl DataStore for FlashDataStore {
    fn all_move_ids(&self, filter: &dyn Fn(&MoveData) -> bool) -> Result<Vec<Id>> {
        let mut ids = Vec::new();
        for (key, json) in MOVES {
            if let Ok(data) = parse::<MoveData>(json) {
                if filter(&data) {
                    ids.push(Id::from(*key));
                }
            }
        }
        Ok(ids)
    }

    fn get_type_chart(&self) -> Result<TypeChart> {
        Ok(self.type_chart.clone())
    }

    fn translate_alias(&self, id: &Id) -> Result<Option<Id>> {
        Ok(find(ALIASES, id).and_then(|json| parse::<Id>(json).ok()))
    }

    fn get_ability(&self, _id: &Id) -> Result<Option<AbilityData>> {
        Ok(None)
    }

    fn get_clause(&self, _id: &Id) -> Result<Option<ClauseData>> {
        Ok(None)
    }

    fn get_condition(&self, id: &Id) -> Result<Option<ConditionData>> {
        match find(CONDITIONS, id) {
            Some(json) => Ok(Some(parse(json)?)),
            None => Ok(None),
        }
    }

    fn get_item(&self, _id: &Id) -> Result<Option<ItemData>> {
        Ok(None)
    }

    fn get_move(&self, id: &Id) -> Result<Option<MoveData>> {
        match find(MOVES, id) {
            Some(json) => Ok(Some(parse(json)?)),
            None => Ok(None),
        }
    }

    fn get_species(&self, id: &Id) -> Result<Option<SpeciesData>> {
        match find(SPECIES, id) {
            Some(json) => Ok(Some(parse(json)?)),
            None => Ok(None),
        }
    }
}
