//! Gen 1 move descriptions, generated by `build.rs` from Pokemon Showdown's
//! `data/text/moves.ts` (gen1-resolved), keyed by canonical move id.

include!(concat!(env!("OUT_DIR"), "/move_descs.rs"));

/// Look up a move's description by display name or id ("Body Slam" or
/// "bodyslam"). `None` when the move has no description entry.
pub fn move_desc(name: &str) -> Option<&'static str> {
    let mut id = [0u8; 24];
    let mut len = 0usize;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if len >= id.len() {
                return None;
            }
            id[len] = c.to_ascii_lowercase() as u8;
            len += 1;
        }
    }
    let id = core::str::from_utf8(&id[..len]).ok()?;
    MOVE_DESCS
        .binary_search_by(|(k, _)| (*k).cmp(id))
        .ok()
        .map(|i| MOVE_DESCS[i].1)
}
