//! Gen 1 mon sprites for the battle screen, generated by `build.rs` from the
//! Game Boy Red/Blue front sprites: 1-bit 48x48, packed row-major (6 bytes
//! per row, MSB = leftmost pixel), keyed by battler display name.

include!(concat!(env!("OUT_DIR"), "/sprites.rs"));

/// Look up a species' sprite by its battler display name (e.g. "Blastoise",
/// "Mr. Mime"). `None` for non-species strings like "FAINTED" or "---".
pub fn mon_sprite(name: &str) -> Option<&'static [u8; 288]> {
    if let Ok(i) = MON_SPRITES.binary_search_by(|(n, _)| (*n).cmp(name)) {
        return Some(&MON_SPRITES[i].1);
    }
    // Fallback for non-canonical casing (e.g. a lowercase id leaking in as a
    // display name): linear case-insensitive scan — 151 entries, miss-only.
    MON_SPRITES
        .iter()
        .find(|(n, _)| n.eq_ignore_ascii_case(name))
        .map(|(_, spr)| spr)
}
