//! Gen 1 mon sprites for the battle screen, generated by `build.rs` from the
//! Game Boy Red/Blue front sprites: 1-bit 48x48, packed row-major (6 bytes
//! per row, MSB = leftmost pixel), keyed by battler display name.

include!(concat!(env!("OUT_DIR"), "/sprites.rs"));

/// Look up a species' sprite by its battler display name (e.g. "Blastoise",
/// "Mr. Mime"). `None` for non-species strings like "FAINTED" or "---".
pub fn mon_sprite(name: &str) -> Option<&'static [u8; 288]> {
    MON_SPRITES
        .binary_search_by(|(n, _)| (*n).cmp(name))
        .ok()
        .map(|i| &MON_SPRITES[i].1)
}
