//! Color mon sprites for the single-screen redesign.
//!
//! Generated by `build.rs` from the Game Boy Red/Blue art at its **native
//! cropped size** — no rescale, no color loss. The source sprites are already
//! 4-shade indexed with a per-species Super Game Boy palette, so 4 bits per
//! pixel plus a 16-entry RGB565 palette reproduces the reference exactly.
//!
//! Pixel data lives in one flat blob (`include_bytes!`) rather than source
//! arrays: 300 sprites of Rust array literals is megabytes of parsing.
//!
//! Back sprites are stored at their native 32x32 and drawn at 2x, which is
//! what the Game Boy itself did.

/// One species' art: a slice of the shared blob plus its palette.
#[derive(Clone, Copy)]
pub struct ColorSprite {
    pub w: u8,
    pub h: u8,
    pub pal_off: u32,
    pub pal_len: u16,
    pub data_off: u32,
    pub data_len: u32,
}

static SPRITE_BLOB: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/sprites_color.bin"));

include!(concat!(env!("OUT_DIR"), "/sprites_color.rs"));

impl ColorSprite {
    /// Palette entry `i` as RGB565. Index 0 is always transparent.
    #[inline]
    pub fn color(&self, i: u8) -> u16 {
        let i = i as usize;
        if i >= self.pal_len as usize {
            return 0;
        }
        let o = self.pal_off as usize + i * 2;
        u16::from_le_bytes([SPRITE_BLOB[o], SPRITE_BLOB[o + 1]])
    }

    /// Palette index at `(x, y)`; 0 means transparent.
    #[inline]
    pub fn index_at(&self, x: u32, y: u32) -> u8 {
        if x >= self.w as u32 || y >= self.h as u32 {
            return 0;
        }
        let row_bytes = (self.w as u32 + 1) / 2;
        let byte = SPRITE_BLOB[(self.data_off + y * row_bytes + x / 2) as usize];
        if x % 2 == 0 { byte >> 4 } else { byte & 0x0F }
    }
}

fn lookup(table: &'static [(&'static str, ColorSprite)], name: &str) -> Option<&'static ColorSprite> {
    if let Ok(i) = table.binary_search_by(|(n, _)| (*n).cmp(name)) {
        return Some(&table[i].1);
    }
    table
        .iter()
        .find(|(n, _)| n.eq_ignore_ascii_case(name))
        .map(|(_, s)| s)
}

/// Front (opponent-facing) art for a species display name.
pub fn mon_sprite_color(name: &str) -> Option<&'static ColorSprite> {
    lookup(MON_SPRITES_COLOR, name)
}

/// What to CALL a species on screen. Formes keep their own art but answer to
/// the base name: a plate reading "Deoxys-Attack" spends half its width on a
/// suffix, and the games call it Deoxys too. The test for a forme is that the
/// part before the hyphen is itself a species we have art for, which leaves
/// Ho-Oh, Nidoran-F and Porygon-Z alone.
pub fn species_display_name(name: &str) -> &str {
    match name.split_once('-') {
        Some((base, _)) if !base.is_empty() && mon_sprite_color(base).is_some() => base,
        _ => name,
    }
}

/// Back (own-side) art, falling back to the front art when missing.
pub fn mon_back_sprite_color(name: &str) -> Option<&'static ColorSprite> {
    lookup(MON_BACK_SPRITES_COLOR, name).or_else(|| mon_sprite_color(name))
}
