[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["probe-rs", "run", "--chip", "RP2040", "--probe", "2e8a:000c:E663589863798621", "--speed", "8000", "--log-format=oneline"]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[env]
DEFMT_LOG = "info"

[build]
target = "thumbv6m-none-eabi"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
