//! Flash-resident static data tables: species, moves, type chart.
//!
//! Generated by `build.rs` from `data/gen1_*.json`. Total flash budget ≈ 10 KB.

use crate::types::Type;

/// One species' base data. ~32 B packed.
#[derive(Clone, Copy, Debug)]
pub struct SpeciesEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub primary_type: Type,
    pub secondary_type: Type, // Type::None for single-typed mons
    /// HP, Atk, Def, Spc, Speed. Gen 1 has no Sp.Atk/Sp.Def split — `spc` is "Special".
    pub base_stats: [u16; 5],
    pub catch_rate: u8,
    pub base_exp_yield: u16,
}

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MoveCategory {
    Physical = 0,
    Special,
    Status,
}

/// The dispatch tag for a move's on-hit behavior. Each variant is implemented
/// in the move executor (task #5 / #6). All Gen 1 moves map to exactly one.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MoveEffectKind {
    /// Plain damage. No rider.
    Damage = 0,
    /// Damage + chance to inflict status. `param0`=status_id, `param1`=chance/256.
    DamageMaybeStatus,
    /// Damage + chance to flinch. `param0`=chance/256.
    DamageMaybeFlinch,
    /// Damage + 85/256 chance to drop a target stat. `param0`=stat_id, `param1`=delta_i8.
    DamageMaybeBoostTarget,
    /// Stage change, self.    `param0`=stat_id, `param1`=delta_i8.
    BoostSelf,
    /// Stage change, target.  `param0`=stat_id, `param1`=delta_i8.
    BoostTarget,
    /// Always inflict status. `param0`=status_id.
    StatusOnly,
    /// Multi-hit (2–5 weighted: 3/8 for 2, 3/8 for 3, 1/8 for 4, 1/8 for 5).
    MultiHit2to5,
    /// Multi-hit fixed N.     `param0`=hits.
    MultiHitFixed,
    /// Twineedle: 2 hits, then one `param1`/256 poison roll after the last.
    Twineedle,
    /// Drain HP (half of damage dealt heals user).
    DrainHp,
    /// Dream Eater: fails unless target sleeps; drains half.
    DreamEater,
    /// Recoil 1/4 of damage dealt.
    Recoil1of4,
    /// Struggle: recoil 1/2 of damage dealt (Gen 1).
    StruggleRecoil,
    /// 1 HP self-damage on miss (Hi Jump Kick / Jump Kick in Gen 1).
    CrashOnMiss,
    /// OHKO. Misses if user.speed < target.speed, else 30% accuracy.
    Ohko,
    /// Force the target to switch. Always fails in trainer battles in Gen 1.
    ForceSwitchTarget,
    /// Fixed damage = user's level.
    LevelDamage,
    /// Fixed damage of `param0`.
    FlatDamage,
    /// Psywave: random 1..=1.5*level.
    Psywave,
    /// Set target HP to 50% (Super Fang).
    HalfHp,
    /// Heal self by 50% max HP.
    HealHalf,
    /// Rest — sleep 2 turns, full heal.
    Rest,
    /// Two-turn move (charge then hit). `param0`=invulnerable_during_charge (0/1).
    TwoTurn,
    /// Bide — store the last-damage register 2–3 turns, return 2×.
    Bide,
    /// Thrash / Petal Dance — locked in 3–4 turns, then confusion.
    ThrashLock,
    /// Rage — locked in until the battle ends; +1 Atk whenever hit.
    Rage,
    /// Hyper Beam (recharge unless KO).
    HyperBeam,
    /// Counter — mirror back 2× last Normal/Fighting damage.
    Counter,
    /// Mirror Move — copy opponent's last move.
    MirrorMove,
    /// Mimic — replace a slot with target's last move (PP=5).
    Mimic,
    /// Transform — copy species/stats/types/moves/stages from target.
    Transform,
    /// Substitute — 1/4 HP + 1 sub.
    Substitute,
    /// Disable — random target move, 1–8 turns.
    Disable,
    /// Wrap-like trap: 2–5 turns, target trapped, small damage per turn.
    Wrap,
    /// Leech Seed — drain 1/16 EOT.
    LeechSeed,
    /// Light Screen — Spc damage doublers for the user's team.
    LightScreen,
    /// Reflect — Phys damage doublers for the user's team.
    Reflect,
    /// Mist — immune to opponent stat reductions while active.
    Mist,
    /// Focus Energy — modifies crit rate (BUGGED: lowers in Gen 1).
    FocusEnergy,
    /// Conversion — copy target's type(s) onto user.
    Conversion,
    /// Haze — clear all stat stages on both sides.
    Haze,
    /// Metronome — choose a random move and execute it.
    Metronome,
    /// Self-Destruct / Explosion — halves target Def (Gen 1), KOs user.
    SelfDestruct,
    /// Splash and other status-no-ops.
    NoOp,
}

/// One move. ~24 B packed.
#[derive(Clone, Copy, Debug)]
pub struct MoveEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub move_type: Type,
    pub category: MoveCategory,
    pub power: u8,        // 0 = no damage
    pub accuracy: u8,     // 0 = always hits (Swift)
    pub pp: u8,
    pub effect_kind: MoveEffectKind,
    pub effect_param0: u8,
    pub effect_param1: u8,
    /// Bit flags — see the FLAG_* constants below.
    pub flags: u8,
}

pub const FLAG_HIGH_CRIT: u8 = 0x01;
pub const FLAG_PRIO_PLUS: u8 = 0x08;
pub const FLAG_PRIO_MINUS: u8 = 0x10;
/// Damaging move that ignores type immunity (fixed damage, partial trapping).
pub const FLAG_IGNORE_IMMUNITY: u8 = 0x20;
/// Hits through Fly/Dig semi-invulnerability (Swift, Transform).
pub const FLAG_HITS_INVULN: u8 = 0x40;

/// Type-effectiveness multiplier ×10: 0 = immune, 5 = ½, 10 = 1×, 20 = 2×.
pub type TypeEffectiveness = u8;

// Generated `SPECIES`, `MOVES`, `TYPE_CHART`, plus lookup helpers.
include!(concat!(env!("OUT_DIR"), "/gen1_tables.rs"));

// ── Lookups ──────────────────────────────────────────────────────────────────

/// Find a species by lowercase ID string. O(log N).
pub fn species_by_id(id: &str) -> Option<&'static SpeciesEntry> {
    SPECIES.binary_search_by(|e| e.id.cmp(id)).ok().map(|i| &SPECIES[i])
}

/// Find a move by lowercase ID string. O(log N).
pub fn move_by_id(id: &str) -> Option<&'static MoveEntry> {
    MOVES.binary_search_by(|e| e.id.cmp(id)).ok().map(|i| &MOVES[i])
}

/// Type-effectiveness multiplier (×10). Use 1× for unknown.
pub fn type_effectiveness(attacker: Type, defender: Type) -> TypeEffectiveness {
    let a = attacker as usize;
    let d = defender as usize;
    if a < TYPE_COUNT && d < TYPE_COUNT {
        TYPE_CHART[a][d]
    } else {
        10
    }
}
