//! Emits the Gen 3 tables into `OUT_DIR/gen3_tables.rs`.
//!
//! Two sources, both already vendored in this repo:
//!
//!   * `../gen1_battle/data/type-chart.json` — the modern chart, read from the
//!     sibling crate rather than copied so the two generations cannot drift
//!     apart on the shared entries.
//!   * `vendor/showdown_gen3_{species,moves}.json` — the era-accurate Gen 3
//!     dex, dumped from Pokémon Showdown's gen3 mod (the parity harness's
//!     `dump` kind regenerates them). Species and moves come from here.
//!   * `../battler/battle-data/data/mons/gen{1,2,3}.json` — still merged, but
//!     ONLY for level-up learnsets, which the dumps do not carry.
//!
//! The species/move tables used to be built by stacking the battler files
//! forward (gen1 then gen2 then gen3). The fuzzer proved that direction wrong:
//! those files are overrides relative to the NEXT gen, so stacking them
//! forward leaked modern PP counts, Gen 6 base-stat buffs, and later forms
//! into a "Gen 3" dex. The Showdown dump is the same source the parity tests
//! validate against, which closes that loop.
//!
//! Gen 3 differs from the modern type chart in exactly two ways, both applied
//! below: Fairy does not exist yet (simply absent from `TYPE_NAMES`), and
//! Steel still resists Ghost and Dark, which both became neutral in Gen 6.
//!
//! Emits:
//!   pub const TYPE_COUNT: usize;
//!   pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT];
//!   * `vendor/gen3randombattle.json` — Showdown's Gen 3 random battle sets,
//!     from pkmn.github.io, cached beside this crate so builds are offline.
//!     This is what a random battle actually draws from, and it is the same
//!     source `mega_blastoise_core` uses for Gen 1. Its sets are curated
//!     movesets per role, which is a different thing from "everything the
//!     species can learn by that level".
//!
//! Emits:
//!   pub const TYPE_COUNT: usize;
//!   pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT];
//!   pub static SPECIES: &[SpeciesEntry];   // sorted by id
//!   pub static MOVES: &[MoveEntry];        // sorted by id
//!   pub static RANDBAT: &[RandbatSet];     // one per species/role pair

use std::{collections::BTreeMap, env, fs, path::PathBuf};

use serde_json::{Map, Value};

/// Attack/defence order for the chart. Must match `types::Type`'s discriminants.
const TYPE_NAMES: &[&str] = &[
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground",
    "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel",
];

/// (attacker, defender, x10 multiplier) where Gen 3 disagrees with the modern
/// chart the JSON describes.
const GEN3_PATCHES: &[(&str, &str, u8)] = &[("Ghost", "Steel", 5), ("Dark", "Steel", 5)];

/// The generations that make up Gen 3's tables, in merge order.
const LAYERS: &[&str] = &["gen1", "gen2", "gen3"];

/// Sentinel in a randbat slot meaning "use the move's own type".
const NO_TYPE_OVERRIDE: u8 = 17;



fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let chart_path = manifest.join("../gen1_battle/data/type-chart.json");
    let data_dir = manifest.join("../battler/battle-data/data");
    println!("cargo:rerun-if-changed=../gen1_battle/data/type-chart.json");
    for layer in LAYERS {
        println!("cargo:rerun-if-changed=../battler/battle-data/data/mons/{layer}.json");
        println!("cargo:rerun-if-changed=../battler/battle-data/data/moves/{layer}.json");
    }

    let mut out = String::from(
        "// @generated by gen3_battle/build.rs — do not edit.\n\n",
    );
    emit_type_chart(&read_json(&chart_path), &mut out);
    println!("cargo:rerun-if-changed=vendor/showdown_gen3_species.json");
    println!("cargo:rerun-if-changed=vendor/showdown_gen3_moves.json");
    let dump_species = read_json(&manifest.join("vendor/showdown_gen3_species.json"));
    let dump_moves = read_json(&manifest.join("vendor/showdown_gen3_moves.json"));
    let learnsets = merge_layers(&data_dir.join("mons"));
    let move_ids = emit_moves(&dump_moves, &mut out);
    emit_species(&dump_species, &learnsets, &move_ids, &mut out);
    emit_randbat(&fetch_randbats(&manifest), &move_ids, &mut out);

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("gen3_tables.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// Showdown's Gen 3 random battle sets, cached so a build never needs the
/// network twice. Mirrors what `mega_blastoise_core` does for Gen 1.
fn fetch_randbats(manifest: &PathBuf) -> Value {
    let vendor = manifest.join("vendor");
    fs::create_dir_all(&vendor).unwrap();
    let cached = vendor.join("gen3randombattle.json");
    println!("cargo:rerun-if-changed=vendor/gen3randombattle.json");
    if !cached.exists() {
        let text = ureq::get("https://pkmn.github.io/randbats/data/gen3randombattle.json")
            .call()
            .unwrap_or_else(|e| panic!("fetch gen3 randbats: {e}"))
            .into_string()
            .unwrap_or_else(|e| panic!("read gen3 randbats: {e}"));
        fs::write(&cached, text).unwrap();
    }
    read_json(&cached)
}

/// Showdown keys its sets by display name ("Mr. Mime"); the dex is keyed by
/// id ("mrmime").
fn species_id(display: &str) -> String {
    display.chars().filter(|c| c.is_ascii_alphanumeric()).flat_map(|c| c.to_lowercase()).collect()
}

fn read_json(path: &PathBuf) -> Value {
    let raw =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

/// Merge `gen1`, `gen2` and `gen3` from `dir`, later layers overriding earlier
/// ones field by field.
fn merge_layers(dir: &PathBuf) -> BTreeMap<String, Map<String, Value>> {
    let mut merged: BTreeMap<String, Map<String, Value>> = BTreeMap::new();
    for layer in LAYERS {
        let path = dir.join(format!("{layer}.json"));
        let obj = read_json(&path);
        let obj = obj.as_object().unwrap_or_else(|| panic!("{} is not an object", path.display()));
        for (id, entry) in obj {
            let entry = match entry.as_object() {
                Some(e) => e,
                None => continue,
            };
            let slot = merged.entry(id.clone()).or_default();
            for (k, v) in entry {
                slot.insert(k.clone(), v.clone());
            }
        }
    }
    merged
}

fn emit_type_chart(chart: &Value, out: &mut String) {
    let types = chart
        .get("types")
        .and_then(|x| x.as_object())
        .expect("type chart is missing its 'types' key");

    out.push_str(&format!("pub const TYPE_COUNT: usize = {};\n", TYPE_NAMES.len()));
    out.push_str("pub static TYPE_CHART: [[TypeEffectiveness; TYPE_COUNT]; TYPE_COUNT] = [\n");
    for atk in TYPE_NAMES {
        out.push_str("    [");
        for def in TYPE_NAMES {
            let mut e = types
                .get(*atk)
                .and_then(|m| m.get(*def))
                .and_then(|v| v.as_f64())
                .map(|mult| (mult * 10.0) as u8)
                .unwrap_or(10);
            for (a, d, patched) in GEN3_PATCHES {
                if a == atk && d == def {
                    e = *patched;
                }
            }
            out.push_str(&format!("{e}, "));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n\n");
}

/// `Type::Foo` for a type name, or a build failure. Never silently Normal: a
/// typo or a type this generation does not have has to stop the build.
fn type_variant(name: &str, ctx: &str) -> String {
    // Curse is the era's one "???"-typed move; it is a status move and its
    // type never reaches the chart.
    if name == "???" {
        return String::from("Type::None");
    }
    if !TYPE_NAMES.contains(&name) {
        panic!("{ctx}: '{name}' is not a Gen 3 type");
    }
    format!("Type::{name}")
}

fn emit_species(
    dump: &Value,
    learnsets: &BTreeMap<String, Map<String, Value>>,
    move_ids: &[String],
    out: &mut String,
) {
    let move_index = |id: &str| move_ids.iter().position(|m| m == id);

    let mut species: Vec<&Map<String, Value>> = dump
        .as_array()
        .expect("species dump is an array")
        .iter()
        .filter_map(|m| m.as_object())
        .collect();
    species.sort_by(|a, b| a["id"].as_str().unwrap().cmp(b["id"].as_str().unwrap()));
    species.dedup_by(|a, b| a["id"] == b["id"]);

    // Flat (move index, level) learnset rows; each species points at a run.
    let mut learn_flat: Vec<(usize, u64)> = Vec::new();
    let mut spans: Vec<(usize, usize)> = Vec::new();
    for m in &species {
        let id = m["id"].as_str().unwrap();
        let start = learn_flat.len();
        if let Some(ls) = learnsets.get(id).and_then(|e| e.get("learnset")).and_then(|v| v.as_object()) {
            let mut rows: Vec<(usize, u64)> = Vec::new();
            for (move_id, sources) in ls {
                let Some(idx) = move_index(move_id) else { continue };
                let Some(list) = sources.as_array() else { continue };
                for src in list {
                    let Some(tag) = src.as_str() else { continue };
                    if let Some(level) = tag.strip_prefix('L').and_then(|n| n.parse::<u64>().ok()) {
                        rows.push((idx, level));
                        break;
                    }
                }
            }
            rows.sort();
            learn_flat.extend(rows);
        }
        spans.push((start, learn_flat.len() - start));
    }

    out.push_str("pub static LEARNSET: &[(u16, u8)] = &[\n");
    for (idx, level) in &learn_flat {
        out.push_str(&format!("({idx}, {level}), "));
    }
    out.push_str("\n];\n\n");
    println!("cargo:warning=gen3_battle: {} learnset rows", learn_flat.len());

    out.push_str("pub static SPECIES: &[SpeciesEntry] = &[\n");
    for (m, (ls_start, ls_len)) in species.iter().zip(&spans) {
        let id = m["id"].as_str().unwrap();
        let name = m["name"].as_str().unwrap();
        let types = m["types"].as_array().unwrap();
        let primary = type_variant(types[0].as_str().unwrap(), id);
        let secondary = match types.get(1).and_then(|t| t.as_str()) {
            Some(t) => type_variant(t, id),
            None => String::from("Type::None"),
        };
        let stats = m["baseStats"].as_object().unwrap();
        let stat = |k: &str| stats[k].as_u64().unwrap() as u16;
        out.push_str(&format!(
            "    SpeciesEntry {{ id: {id:?}, name: {name:?}, types: ({primary}, {secondary}), \
             base: BaseStats {{ hp: {}, atk: {}, def: {}, spa: {}, spd: {}, spe: {} }}, \
             learn_start: {ls_start}, learn_len: {ls_len} }},\n",
            stat("hp"), stat("atk"), stat("def"), stat("spa"), stat("spd"), stat("spe"),
        ));
    }
    out.push_str("];\n\n");
    println!("cargo:warning=gen3_battle: {} species", species.len());
}

/// One drafted set: a species, the level it is drafted at, and a role's move
/// pool as indices into `MOVES`.
fn emit_randbat(randbats: &Value, move_ids: &[String], out: &mut String) {
    // A set names Hidden Power by the type its IVs give it ("Hidden Power
    // Ice"). The move table has one `hiddenpower`, because in Gen 3 the type
    // is a property of the mon, not of the move. So a set slot carries an
    // optional type override, and Hidden Power is the only thing that uses it.
    let move_index = |display: &str| -> Option<(usize, u8)> {
        let id = species_id(display);
        if let Some(i) = move_ids.iter().position(|m| *m == id) {
            return Some((i, NO_TYPE_OVERRIDE));
        }
        let rest = display.strip_prefix("Hidden Power ")?;
        let hp = move_ids.iter().position(|m| *m == "hiddenpower")?;
        let ty = TYPE_NAMES.iter().position(|t| *t == rest)? as u8;
        Some((hp, ty))
    };

    let obj = randbats.as_object().expect("randbats is an object");
    let mut flat: Vec<(usize, u8)> = Vec::new();
    let mut sets: Vec<(String, u64, usize, usize)> = Vec::new();
    let mut dropped = 0;
    for (display, entry) in obj {
        let id = species_id(display);
        let level = entry.get("level").and_then(|v| v.as_u64()).unwrap_or(50);
        let Some(roles) = entry.get("roles").and_then(|v| v.as_object()) else { continue };
        for role in roles.values() {
            let Some(list) = role.get("moves").and_then(|v| v.as_array()) else { continue };
            let start = flat.len();
            for m in list {
                let Some(name) = m.as_str() else { continue };
                match move_index(name) {
                    Some(pair) => flat.push(pair),
                    // A set naming a move this generation's table lacks is a
                    // data mismatch worth seeing, not worth failing on.
                    None => dropped += 1,
                }
            }
            if flat.len() > start {
                sets.push((id.clone(), level, start, flat.len() - start));
            }
        }
    }

    out.push_str("pub static RANDBAT_MOVES: &[(u16, u8)] = &[\n");
    for (i, ty) in &flat {
        out.push_str(&format!("({i}, {ty}), "));
    }
    out.push_str("\n];\n\n");
    out.push_str("pub static RANDBAT: &[RandbatSet] = &[\n");
    for (id, level, start, len) in &sets {
        out.push_str(&format!(
            "    RandbatSet {{ species: {id:?}, level: {level}, move_start: {start}, move_len: {len} }},\n"
        ));
    }
    out.push_str("];\n\n");
    println!("cargo:warning=gen3_battle: {} randbat sets, {dropped} moves not in the gen3 table", sets.len());
}

fn emit_moves(dump: &Value, out: &mut String) -> Vec<String> {
    let mut moves: Vec<&Map<String, Value>> = dump
        .as_array()
        .expect("moves dump is an array")
        .iter()
        .filter_map(|m| m.as_object())
        .collect();
    moves.sort_by(|a, b| a["id"].as_str().unwrap().cmp(b["id"].as_str().unwrap()));
    moves.dedup_by(|a, b| a["id"] == b["id"]);

    out.push_str("pub static MOVES: &[MoveEntry] = &[\n");
    let mut ids = Vec::new();
    for m in &moves {
        let id = m["id"].as_str().unwrap();
        let name = m["name"].as_str().unwrap();
        let mtype = m["type"].as_str().unwrap();
        let power = m["basePower"].as_u64().unwrap_or(0) as u16;
        let accuracy = m["accuracy"].as_u64().unwrap_or(0) as u8;
        let pp = m["pp"].as_u64().unwrap_or(0) as u8;
        let priority = m["priority"].as_i64().unwrap_or(0) as i8;
        let secondary = match m["secondary"].as_object() {
            Some(sec) => {
                let chance = sec["chance"].as_u64().unwrap_or(0) as u8;
                let effect = if let Some(status) = sec.get("status").and_then(|v| v.as_str()) {
                    let status = match status {
                        "brn" => "Status::Burn",
                        "par" => "Status::Paralysis",
                        "psn" => "Status::Poison",
                        "tox" => "Status::Toxic",
                        "frz" => "Status::Freeze",
                        "slp" => "Status::Sleep",
                        other => panic!("{id}: unknown secondary status {other:?}"),
                    };
                    format!("SecondaryEffect::Status({status})")
                } else if sec.get("flinch").is_some() {
                    String::from("SecondaryEffect::Flinch")
                } else if sec.get("confusion").is_some() {
                    String::from("SecondaryEffect::Confuse")
                } else if let Some(boosts) = sec.get("boosts").and_then(|v| v.as_object()) {
                    let items: Vec<String> = boosts
                        .iter()
                        .map(|(stat, delta)| {
                            let boost = match stat.as_str() {
                                "atk" => "Boost::Atk",
                                "def" => "Boost::Def",
                                "spa" => "Boost::SpAtk",
                                "spd" => "Boost::SpDef",
                                "spe" => "Boost::Spe",
                                "accuracy" => "Boost::Acc",
                                "evasion" => "Boost::Eva",
                                other => panic!("{id}: unknown boost stat {other:?}"),
                            };
                            format!("({boost}, {})", delta.as_i64().unwrap())
                        })
                        .collect();
                    format!("SecondaryEffect::Boosts(&[{}])", items.join(", "))
                } else {
                    panic!("{id}: secondary carries neither status nor boosts")
                };
                format!("Some(Secondary {{ chance: {chance}, effect: {effect} }})")
            }
            None => String::from("None"),
        };
        let fraction = |key: &str| match m[key].as_array() {
            Some(pair) => format!(
                "Some(({}, {}))",
                pair[0].as_u64().unwrap(),
                pair[1].as_u64().unwrap()
            ),
            None => String::from("None"),
        };
        let (drain, recoil) = (fraction("drain"), fraction("recoil"));
        let multihit = fraction("multihit");
        let boost_list = |boosts: &Map<String, Value>| -> String {
            let items: Vec<String> = boosts
                .iter()
                .map(|(stat, delta)| {
                    let boost = match stat.as_str() {
                        "atk" => "Boost::Atk",
                        "def" => "Boost::Def",
                        "spa" => "Boost::SpAtk",
                        "spd" => "Boost::SpDef",
                        "spe" => "Boost::Spe",
                        "accuracy" => "Boost::Acc",
                        "evasion" => "Boost::Eva",
                        other => panic!("{id}: unknown boost stat {other:?}"),
                    };
                    format!("({boost}, {})", delta.as_i64().unwrap())
                })
                .collect();
            format!("&[{}]", items.join(", "))
        };
        let respects_immunity = m["respectsImmunity"].as_bool().unwrap_or(false);
        let fixed = match &m["fixed"] {
            Value::Number(n) => format!("Some(FixedDamage::Flat({}))", n.as_u64().unwrap()),
            Value::String(kind) => match kind.as_str() {
                "level" => String::from("Some(FixedDamage::Level)"),
                "half" => String::from("Some(FixedDamage::Half)"),
                other => panic!("{id}: unknown fixed damage kind {other:?}"),
            },
            _ => String::from("None"),
        };
        let ohko = m["ohko"].as_bool().unwrap_or(false);
        let high_crit = m["highCrit"].as_bool().unwrap_or(false);
        let selfdestruct = m["selfdestruct"].as_bool().unwrap_or(false);
        let status_action = match m["statusAction"].as_object() {
            None => String::from("None"),
            Some(act) => {
                if let Some(status) = act.get("status").and_then(|v| v.as_str()) {
                    let status = match status {
                        "brn" => "Status::Burn",
                        "par" => "Status::Paralysis",
                        "psn" => "Status::Poison",
                        "tox" => "Status::Toxic",
                        "frz" => "Status::Freeze",
                        "slp" => "Status::Sleep",
                        other => panic!("{id}: unknown inflicted status {other:?}"),
                    };
                    format!("Some(StatusAction::Inflict({status}))")
                } else if let Some(heal) = act.get("heal").and_then(|v| v.as_array()) {
                    assert_eq!(
                        (heal[0].as_u64(), heal[1].as_u64()),
                        (Some(1), Some(2)),
                        "{id}: only half heals are modelled"
                    );
                    String::from("Some(StatusAction::HealHalf)")
                } else if act.get("confuse").is_some() {
                    String::from("Some(StatusAction::Confuse)")
                } else if let Some(boosts) = act.get("boosts").and_then(|v| v.as_object()) {
                    let variant = if act.get("self").and_then(|v| v.as_bool()).unwrap_or(false) {
                        "BoostSelf"
                    } else {
                        "BoostFoe"
                    };
                    format!("Some(StatusAction::{variant}({}))", boost_list(boosts))
                } else {
                    panic!("{id}: statusAction carries nothing modelled")
                }
            }
        };
        out.push_str(&format!(
            "    MoveEntry {{ id: {id:?}, name: {name:?}, move_type: {}, \
             power: {power}, accuracy: {accuracy}, pp: {pp}, priority: {priority}, \
             secondary: {secondary}, drain: {drain}, recoil: {recoil}, \
             multihit: {multihit}, status_action: {status_action}, \
             respects_immunity: {respects_immunity}, fixed: {fixed}, \
             ohko: {ohko}, high_crit: {high_crit}, selfdestruct: {selfdestruct} }},\n",
            type_variant(mtype, id),
        ));
        ids.push(id.to_string());
    }
    out.push_str("];\n\n");
    println!("cargo:warning=gen3_battle: {} moves", ids.len());
    ids
}
