use std::{
    collections::BTreeMap,
    env, fs,
    io::Read,
    path::{Path, PathBuf},
};

use ciborium::ser::into_writer;

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let data_root = manifest.join("../battler/battle-data/data");

    println!("cargo:rerun-if-changed={}", data_root.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let type_chart = load_json(&data_root, "type-chart.json");
    let aliases = load_json(&data_root, "aliases.json");
    let abilities = load_json(&data_root, "abilities/gen1.json");
    let conditions = merge_json_files(&data_root, &["conditions.json", "move-bases.json"]);
    let mons = slim_mons(load_json(&data_root, "mons/gen1.json"));
    let moves = slim_moves(load_json(&data_root, "moves/gen1.json"));

    let mut out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: battler/battle-data/data  (gen 1)\n\n",
    );

    // TYPE_CHART values are TypeEffectiveness, which deserializes via deserialize_f32.
    // ciborium is strict about float vs integer CBOR types, so normalize integers to f64
    // (0 → 0.0, 1 → 1.0, 2 → 2.0) so they round-trip through TypeEffectiveness::Deserialize.
    emit_cbor_table(&mut out, "TYPE_CHART", &integers_to_floats(type_chart));
    emit_cbor_table(&mut out, "ALIASES", &aliases);
    emit_cbor_table(&mut out, "ABILITIES", &abilities);
    emit_cbor_table(&mut out, "CONDITIONS", &conditions);
    emit_cbor_table(&mut out, "SPECIES", &mons);
    emit_cbor_table(&mut out, "MOVES", &moves);

    fs::write(out_dir.join("battle_data.rs"), out).unwrap();

    // ── Randbat roster ────────────────────────────────────────────────────────
    let randbats = fetch_randbats(manifest);
    let mut roster_out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: https://pkmn.github.io/randbats/data/gen1randombattle.json\n\n",
    );
    emit_roster(&mut roster_out, &randbats, &mons, &moves);
    fs::write(out_dir.join("roster.rs"), roster_out).unwrap();

    // ── Gen 1 OLED sprites ────────────────────────────────────────────────────
    let mut sprites_out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: Game Boy Red/Blue front sprites (PokeAPI sprite repo),\n\
         // converted to 1-bit 48x48: pixels brighter than the dark-gray shade\n\
         // are lit, the black outline stays dark (backlit Game Boy look).\n\n",
    );
    emit_sprites(&mut sprites_out, manifest);
    fs::write(out_dir.join("sprites.rs"), sprites_out).unwrap();
}

fn load_json(root: &Path, rel: &str) -> serde_json::Value {
    let path = root.join(rel);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("bad JSON in {}: {e}", path.display()))
}

fn merge_json_files(root: &Path, files: &[&str]) -> serde_json::Value {
    let mut merged = serde_json::Map::new();
    for f in files {
        if let serde_json::Value::Object(m) = load_json(root, f) {
            merged.extend(m);
        }
    }
    serde_json::Value::Object(merged)
}

fn slim_mons(val: serde_json::Value) -> serde_json::Value {
    let heavy = ["learnset", "events", "evos", "prevo", "evolution_data",
                 "formes", "cosmetic_formes", "base_forme", "changes_from",
                 "gigantamax_move", "required_moves", "required_items"];
    map_object_values(val, |mut obj| {
        for key in &heavy {
            obj.remove(*key);
        }
        obj
    })
}

fn slim_moves(val: serde_json::Value) -> serde_json::Value {
    map_object_values(val, |mut obj| {
        obj.remove("effect");
        obj.remove("condition");
        obj
    })
}

fn map_object_values(
    val: serde_json::Value,
    f: impl Fn(serde_json::Map<String, serde_json::Value>) -> serde_json::Map<String, serde_json::Value>,
) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => {
            let out = map
                .into_iter()
                .map(|(k, v)| {
                    let slimmed = match v {
                        serde_json::Value::Object(inner) => serde_json::Value::Object(f(inner)),
                        other => other,
                    };
                    (k, slimmed)
                })
                .collect();
            serde_json::Value::Object(out)
        }
        other => other,
    }
}

fn emit_cbor_table(out: &mut String, name: &str, val: &serde_json::Value) {
    let map: BTreeMap<&str, &serde_json::Value> = match val {
        serde_json::Value::Object(m) => m.iter().map(|(k, v)| (k.as_str(), v)).collect(),
        _ => {
            let bytes = cbor_encode(val);
            out.push_str(&format!(
                "pub static {name}: &[(&str, &[u8])] = &[\n    (\"\", &{raw}),\n];\n\n",
                raw = bytes_literal(&bytes),
            ));
            return;
        }
    };

    out.push_str(&format!("pub static {name}: &[(&str, &[u8])] = &[\n"));
    for (k, v) in &map {
        let bytes = cbor_encode(v);
        out.push_str(&format!(
            "    ({key}, &{val}),\n",
            key = escaped_raw_str(k),
            val = bytes_literal(&bytes),
        ));
    }
    out.push_str("];\n\n");
}

/// Recursively convert integer JSON numbers to f64 so ciborium encodes them as CBOR floats.
/// Only used for the TYPE_CHART, where TypeEffectiveness::Deserialize calls deserialize_f32
/// and ciborium refuses to coerce CBOR integers to floats.
fn integers_to_floats(val: serde_json::Value) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => serde_json::Value::Object(
            map.into_iter().map(|(k, v)| (k, integers_to_floats(v))).collect(),
        ),
        serde_json::Value::Array(arr) => {
            serde_json::Value::Array(arr.into_iter().map(integers_to_floats).collect())
        }
        serde_json::Value::Number(n) if n.is_u64() || n.is_i64() => {
            let f = n.as_f64().expect("integer fits f64");
            serde_json::Value::Number(serde_json::Number::from_f64(f).unwrap())
        }
        other => other,
    }
}

fn cbor_encode(val: &serde_json::Value) -> Vec<u8> {
    let mut bytes = Vec::new();
    into_writer(val, &mut bytes).unwrap_or_else(|e| panic!("CBOR encode failed: {e}"));
    bytes
}

fn bytes_literal(bytes: &[u8]) -> String {
    let entries: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
    format!("[{}]", entries.join(", "))
}

fn escaped_raw_str(s: &str) -> String {
    let mut hashes = 0usize;
    loop {
        let delim = "#".repeat(hashes);
        if !s.contains(&format!("\"{})", delim)) && !s.contains(&format!("\"{}", delim)) {
            return format!("r{delim}\"{s}\"{delim}");
        }
        hashes += 1;
    }
}

/// Fetch (and cache) the Gen 1 Random Battle data from pkmn.github.io.
///
/// The file is cached at `vendor/gen1randombattle.json` next to Cargo.toml so
/// that subsequent builds don't need network access.
fn fetch_randbats(manifest: &Path) -> serde_json::Value {
    let vendor = manifest.join("vendor");
    fs::create_dir_all(&vendor).unwrap();
    let cached = vendor.join("gen1randombattle.json");

    println!("cargo:rerun-if-changed={}", cached.display());

    if !cached.exists() {
        let text = ureq::get("https://pkmn.github.io/randbats/data/gen1randombattle.json")
            .call()
            .unwrap_or_else(|e| panic!("failed to fetch randbats JSON: {e}"))
            .into_string()
            .unwrap_or_else(|e| panic!("failed to read randbats response: {e}"));
        fs::write(&cached, &text).unwrap();
    }

    let text = fs::read_to_string(&cached).unwrap();
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("bad JSON in gen1randombattle.json: {e}"))
}

/// Codegen the `RANDBAT_POOL` static into `out`.
///
/// The randbats JSON already uses capitalized species names as keys and full
/// display names in the moves array, so no lookup into the battle-data tables
/// is needed.  The `RandBatEntry` struct is defined in `randbat.rs`; this
/// function only emits the static array initialiser.
fn emit_roster(
    out: &mut String,
    randbats: &serde_json::Value,
    _mons: &serde_json::Value,
    _moves: &serde_json::Value,
) {
    let map = match randbats {
        serde_json::Value::Object(m) => m,
        _ => panic!("randbats JSON is not an object"),
    };

    out.push_str("pub static RANDBAT_POOL: &[RandBatEntry] = &[\n");

    for (species, entry) in map.iter() {
        let level = entry.get("level")
            .and_then(|l| l.as_u64())
            .unwrap_or(50) as u8;

        let move_names: Vec<&str> = entry
            .get("moves")
            .and_then(|m| m.as_array())
            .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();

        if move_names.is_empty() {
            continue;
        }

        let moves_lit = move_names
            .iter()
            .map(|m| escaped_raw_str(m))
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str(&format!(
            "    RandBatEntry {{ species: {sp}, level: {lv}, moves: &[{mv}] }},\n",
            sp = escaped_raw_str(species),
            lv = level,
            mv = moves_lit,
        ));
    }

    out.push_str("];\n");
}

// ── Gen 1 OLED sprites ───────────────────────────────────────────────────────

/// Rendered sprite side length in pixels. The default 48 fits between the
/// two corner-move text rows on the 128x64 OLED (rows 8..56). The `bigsprite`
/// build variant uses a 56px canvas with the Game Boy sprites placed 1:1
/// (un-rescaled; GB front sprites are at most 56x56) — the corner move text
/// draws over the sprite's margins.
fn sprite_side() -> usize {
    if std::env::var("CARGO_FEATURE_BIGSPRITE").is_ok() { 56 } else { 48 }
}

/// The 151 Gen 1 species in dex order, using battler's display names
/// (`mons/gen1.json` `name` fields) so `render_player_screen` can match the
/// name it is handed. Index + 1 = national dex number = sprite file name.
const GEN1_DEX: [&str; 151] = [
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
    "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot",
    "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok",
    "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran-F", "Nidorina",
    "Nidoqueen", "Nidoran-M", "Nidorino", "Nidoking", "Clefairy", "Clefable",
    "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat",
    "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat",
    "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck",
    "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag",
    "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop",
    "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool",
    "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash",
    "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch'd", "Doduo",
    "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder",
    "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee",
    "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute",
    "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung",
    "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela",
    "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu",
    "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar",
    "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto",
    "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte",
    "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno",
    "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew",
];

/// Fetch (and cache) one R/B front sprite PNG, like `fetch_randbats`:
/// cached under `vendor/sprites/` so builds after the first are offline.
fn fetch_sprite(manifest: &Path, dex: usize) -> PathBuf {
    let dir = manifest.join("vendor/sprites");
    fs::create_dir_all(&dir).unwrap();
    let cached = dir.join(format!("{dex}.png"));
    if !cached.exists() {
        let url = format!(
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/{dex}.png"
        );
        let mut bytes = Vec::new();
        ureq::get(&url)
            .call()
            .unwrap_or_else(|e| panic!("failed to fetch sprite {dex}: {e}"))
            .into_reader()
            .read_to_end(&mut bytes)
            .unwrap_or_else(|e| panic!("failed to read sprite {dex}: {e}"));
        fs::write(&cached, &bytes).unwrap();
    }
    cached
}

/// Decode a sprite PNG into an "ink" mask at source resolution, cropped to
/// content: `true` where the pixel is opaque AND brighter than the dark-gray
/// shade (luma > 100). The black outline and dark shade stay `false`, which
/// on the OLED reads as a backlit Game Boy sprite.
fn sprite_ink(path: &Path) -> Vec<Vec<bool>> {
    let mut decoder = png::Decoder::new(fs::File::open(path).unwrap());
    decoder.set_transformations(png::Transformations::EXPAND | png::Transformations::ALPHA);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();
    let (w, h) = (info.width as usize, info.height as usize);
    let ch = match info.color_type {
        png::ColorType::Rgba => 4,
        png::ColorType::GrayscaleAlpha => 2,
        other => panic!("{}: unexpected color type {other:?} after EXPAND|ALPHA", path.display()),
    };

    let px = |x: usize, y: usize| -> (u32, u8) {
        let p = &buf[(y * w + x) * ch..];
        match ch {
            4 => ((299 * p[0] as u32 + 587 * p[1] as u32 + 114 * p[2] as u32) / 1000, p[3]),
            _ => (p[0] as u32, p[1]),
        }
    };

    // content bounding box (opaque pixels)
    let (mut x0, mut y0, mut x1, mut y1) = (w, h, 0usize, 0usize);
    for y in 0..h {
        for x in 0..w {
            if px(x, y).1 > 0 {
                x0 = x0.min(x); y0 = y0.min(y);
                x1 = x1.max(x); y1 = y1.max(y);
            }
        }
    }
    assert!(x0 <= x1, "{}: fully transparent sprite", path.display());

    (y0..=y1)
        .map(|y| (x0..=x1).map(|x| { let (l, a) = px(x, y); a > 0 && l > 100 }).collect())
        .collect()
}

/// Center an ink mask 1:1 on a `side`-square canvas (bigsprite variant).
/// Falls back to scaling if a crop somehow exceeds the canvas.
fn center_ink(ink: &[Vec<bool>], side: usize) -> Vec<Vec<bool>> {
    let (sh, sw) = (ink.len(), ink[0].len());
    if sh > side || sw > side {
        return scale_ink(ink, side);
    }
    let (oy, ox) = ((side - sh) / 2, (side - sw) / 2);
    let mut out = vec![vec![false; side]; side];
    for (y, row) in ink.iter().enumerate() {
        for (x, &lit) in row.iter().enumerate() {
            out[oy + y][ox + x] = lit;
        }
    }
    out
}

/// Scale an ink mask to fit `side` (aspect preserved, centered on a
/// square): each destination pixel lights if lit source pixels cover more
/// than half of its footprint (exact box-overlap coverage).
fn scale_ink(ink: &[Vec<bool>], side: usize) -> Vec<Vec<bool>> {
    let (sh, sw) = (ink.len(), ink[0].len());
    let (nh, nw) = if sh >= sw {
        (side, ((sw * side + sh / 2) / sh).max(1))
    } else {
        (((sh * side + sw / 2) / sw).max(1), side)
    };
    let (oy, ox) = ((side - nh) / 2, (side - nw) / 2);

    let mut out = vec![vec![false; side]; side];
    for dy in 0..nh {
        let (sy0, sy1) = (dy as f64 * sh as f64 / nh as f64, (dy + 1) as f64 * sh as f64 / nh as f64);
        for dx in 0..nw {
            let (sx0, sx1) = (dx as f64 * sw as f64 / nw as f64, (dx + 1) as f64 * sw as f64 / nw as f64);
            let mut cover = 0f64;
            for sy in sy0.floor() as usize..(sy1.ceil() as usize).min(sh) {
                let wy = (sy1.min((sy + 1) as f64) - sy0.max(sy as f64)).max(0.0);
                for sx in sx0.floor() as usize..(sx1.ceil() as usize).min(sw) {
                    if ink[sy][sx] {
                        cover += wy * (sx1.min((sx + 1) as f64) - sx0.max(sx as f64)).max(0.0);
                    }
                }
            }
            out[oy + dy][ox + dx] = cover / ((sy1 - sy0) * (sx1 - sx0)) > 0.5;
        }
    }
    out
}

/// Codegen `MON_SPRITES`: name-sorted `(name, packed 1-bit 48x48)` pairs.
/// Packed row-major, 6 bytes per row, MSB = leftmost pixel — the layout
/// `embedded_graphics::image::ImageRaw::<BinaryColor>` expects.
fn emit_sprites(out: &mut String, manifest: &Path) {
    println!("cargo:rerun-if-changed={}", manifest.join("vendor/sprites").display());
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_BIGSPRITE");
    let side = sprite_side();
    let bytes = side * side / 8;
    let big = std::env::var("CARGO_FEATURE_BIGSPRITE").is_ok();

    let mut entries: Vec<(&str, Vec<u8>)> = GEN1_DEX
        .iter()
        .enumerate()
        .map(|(i, name)| {
            let ink = sprite_ink(&fetch_sprite(manifest, i + 1));
            let canvas = if big { center_ink(&ink, side) } else { scale_ink(&ink, side) };
            let mut packed = vec![0u8; bytes];
            for (y, row) in canvas.iter().enumerate() {
                for (x, &lit) in row.iter().enumerate() {
                    if lit {
                        packed[y * side / 8 + x / 8] |= 0x80 >> (x % 8);
                    }
                }
            }
            (*name, packed)
        })
        .collect();
    entries.sort_by_key(|(name, _)| *name);

    out.push_str(&format!("pub const SPRITE_SIDE: u32 = {side};\n"));
    out.push_str(&format!("pub const SPRITE_BYTES: usize = {bytes};\n\n"));
    out.push_str(&format!(
        "pub static MON_SPRITES: &[(&str, [u8; {bytes}])] = &[\n"
    ));
    for (name, packed) in &entries {
        out.push_str(&format!(
            "    ({key}, {val}),\n",
            key = escaped_raw_str(name),
            val = bytes_literal(packed),
        ));
    }
    out.push_str("];\n");
}

