use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};

use ciborium::ser::into_writer;

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let data_root = manifest.join("../battler/battle-data/data");

    println!("cargo:rerun-if-changed={}", data_root.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let type_chart = load_json(&data_root, "type-chart.json");
    let aliases = load_json(&data_root, "aliases.json");
    let abilities = load_json(&data_root, "abilities/gen1.json");
    let conditions = merge_json_files(&data_root, &["conditions.json", "move-bases.json"]);
    let mons = slim_mons(load_json(&data_root, "mons/gen1.json"));
    let moves = slim_moves(load_json(&data_root, "moves/gen1.json"));

    let mut out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: battler/battle-data/data  (gen 1)\n\n",
    );

    // TYPE_CHART values are TypeEffectiveness, which deserializes via deserialize_f32.
    // ciborium is strict about float vs integer CBOR types, so normalize integers to f64
    // (0 → 0.0, 1 → 1.0, 2 → 2.0) so they round-trip through TypeEffectiveness::Deserialize.
    emit_cbor_table(&mut out, "TYPE_CHART", &integers_to_floats(type_chart));
    emit_cbor_table(&mut out, "ALIASES", &aliases);
    emit_cbor_table(&mut out, "ABILITIES", &abilities);
    emit_cbor_table(&mut out, "CONDITIONS", &conditions);
    emit_cbor_table(&mut out, "SPECIES", &mons);
    emit_cbor_table(&mut out, "MOVES", &moves);

    fs::write(out_dir.join("battle_data.rs"), out).unwrap();

    // ── Randbat roster ────────────────────────────────────────────────────────
    let randbats = fetch_randbats(manifest);
    let mut roster_out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: https://pkmn.github.io/randbats/data/gen1randombattle.json\n\n",
    );
    emit_roster(&mut roster_out, &randbats, &mons, &moves);
    fs::write(out_dir.join("roster.rs"), roster_out).unwrap();
}

fn load_json(root: &Path, rel: &str) -> serde_json::Value {
    let path = root.join(rel);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("bad JSON in {}: {e}", path.display()))
}

fn merge_json_files(root: &Path, files: &[&str]) -> serde_json::Value {
    let mut merged = serde_json::Map::new();
    for f in files {
        if let serde_json::Value::Object(m) = load_json(root, f) {
            merged.extend(m);
        }
    }
    serde_json::Value::Object(merged)
}

fn slim_mons(val: serde_json::Value) -> serde_json::Value {
    let heavy = ["learnset", "events", "evos", "prevo", "evolution_data",
                 "formes", "cosmetic_formes", "base_forme", "changes_from",
                 "gigantamax_move", "required_moves", "required_items"];
    map_object_values(val, |mut obj| {
        for key in &heavy {
            obj.remove(*key);
        }
        obj
    })
}

fn slim_moves(val: serde_json::Value) -> serde_json::Value {
    map_object_values(val, |mut obj| {
        obj.remove("effect");
        obj.remove("condition");
        obj
    })
}

fn map_object_values(
    val: serde_json::Value,
    f: impl Fn(serde_json::Map<String, serde_json::Value>) -> serde_json::Map<String, serde_json::Value>,
) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => {
            let out = map
                .into_iter()
                .map(|(k, v)| {
                    let slimmed = match v {
                        serde_json::Value::Object(inner) => serde_json::Value::Object(f(inner)),
                        other => other,
                    };
                    (k, slimmed)
                })
                .collect();
            serde_json::Value::Object(out)
        }
        other => other,
    }
}

fn emit_cbor_table(out: &mut String, name: &str, val: &serde_json::Value) {
    let map: BTreeMap<&str, &serde_json::Value> = match val {
        serde_json::Value::Object(m) => m.iter().map(|(k, v)| (k.as_str(), v)).collect(),
        _ => {
            let bytes = cbor_encode(val);
            out.push_str(&format!(
                "pub static {name}: &[(&str, &[u8])] = &[\n    (\"\", &{raw}),\n];\n\n",
                raw = bytes_literal(&bytes),
            ));
            return;
        }
    };

    out.push_str(&format!("pub static {name}: &[(&str, &[u8])] = &[\n"));
    for (k, v) in &map {
        let bytes = cbor_encode(v);
        out.push_str(&format!(
            "    ({key}, &{val}),\n",
            key = escaped_raw_str(k),
            val = bytes_literal(&bytes),
        ));
    }
    out.push_str("];\n\n");
}

/// Recursively convert integer JSON numbers to f64 so ciborium encodes them as CBOR floats.
/// Only used for the TYPE_CHART, where TypeEffectiveness::Deserialize calls deserialize_f32
/// and ciborium refuses to coerce CBOR integers to floats.
fn integers_to_floats(val: serde_json::Value) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => serde_json::Value::Object(
            map.into_iter().map(|(k, v)| (k, integers_to_floats(v))).collect(),
        ),
        serde_json::Value::Array(arr) => {
            serde_json::Value::Array(arr.into_iter().map(integers_to_floats).collect())
        }
        serde_json::Value::Number(n) if n.is_u64() || n.is_i64() => {
            let f = n.as_f64().expect("integer fits f64");
            serde_json::Value::Number(serde_json::Number::from_f64(f).unwrap())
        }
        other => other,
    }
}

fn cbor_encode(val: &serde_json::Value) -> Vec<u8> {
    let mut bytes = Vec::new();
    into_writer(val, &mut bytes).unwrap_or_else(|e| panic!("CBOR encode failed: {e}"));
    bytes
}

fn bytes_literal(bytes: &[u8]) -> String {
    let entries: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
    format!("[{}]", entries.join(", "))
}

fn escaped_raw_str(s: &str) -> String {
    let mut hashes = 0usize;
    loop {
        let delim = "#".repeat(hashes);
        if !s.contains(&format!("\"{})", delim)) && !s.contains(&format!("\"{}", delim)) {
            return format!("r{delim}\"{s}\"{delim}");
        }
        hashes += 1;
    }
}

/// Fetch (and cache) the Gen 1 Random Battle data from pkmn.github.io.
///
/// The file is cached at `vendor/gen1randombattle.json` next to Cargo.toml so
/// that subsequent builds don't need network access.
fn fetch_randbats(manifest: &Path) -> serde_json::Value {
    let vendor = manifest.join("vendor");
    fs::create_dir_all(&vendor).unwrap();
    let cached = vendor.join("gen1randombattle.json");

    println!("cargo:rerun-if-changed={}", cached.display());

    if !cached.exists() {
        let text = ureq::get("https://pkmn.github.io/randbats/data/gen1randombattle.json")
            .call()
            .unwrap_or_else(|e| panic!("failed to fetch randbats JSON: {e}"))
            .into_string()
            .unwrap_or_else(|e| panic!("failed to read randbats response: {e}"));
        fs::write(&cached, &text).unwrap();
    }

    let text = fs::read_to_string(&cached).unwrap();
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("bad JSON in gen1randombattle.json: {e}"))
}

/// Codegen the `RANDBAT_POOL` static into `out`.
///
/// The randbats JSON already uses capitalized species names as keys and full
/// display names in the moves array, so no lookup into the battle-data tables
/// is needed.  The `RandBatEntry` struct is defined in `randbat.rs`; this
/// function only emits the static array initialiser.
fn emit_roster(
    out: &mut String,
    randbats: &serde_json::Value,
    _mons: &serde_json::Value,
    _moves: &serde_json::Value,
) {
    let map = match randbats {
        serde_json::Value::Object(m) => m,
        _ => panic!("randbats JSON is not an object"),
    };

    out.push_str("pub static RANDBAT_POOL: &[RandBatEntry] = &[\n");

    for (species, entry) in map.iter() {
        let level = entry.get("level")
            .and_then(|l| l.as_u64())
            .unwrap_or(50) as u8;

        let move_names: Vec<&str> = entry
            .get("moves")
            .and_then(|m| m.as_array())
            .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();

        if move_names.is_empty() {
            continue;
        }

        let moves_lit = move_names
            .iter()
            .map(|m| escaped_raw_str(m))
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str(&format!(
            "    RandBatEntry {{ species: {sp}, level: {lv}, moves: &[{mv}] }},\n",
            sp = escaped_raw_str(species),
            lv = level,
            mv = moves_lit,
        ));
    }

    out.push_str("];\n");
}

