use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let data_root = manifest.join("../../battler/battle-data/data");

    println!("cargo:rerun-if-changed={}", data_root.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let type_chart = load_json(&data_root, "type-chart.json");
    let aliases = load_json(&data_root, "aliases.json");
    let conditions = merge_json_files(&data_root, &["conditions.json", "move-bases.json"]);
    let mons = slim_mons(load_json(&data_root, "mons/gen1.json"));
    let moves = slim_moves(load_json(&data_root, "moves/gen1.json"));

    let mut out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source: battler/battle-data/data  (gen 1)\n\n",
    );

    emit_kv_table(&mut out, "TYPE_CHART", &type_chart);
    emit_kv_table(&mut out, "ALIASES", &aliases);
    emit_kv_table(&mut out, "CONDITIONS", &conditions);
    emit_kv_table(&mut out, "SPECIES", &mons);
    emit_kv_table(&mut out, "MOVES", &moves);

    fs::write(out_dir.join("battle_data.rs"), out).unwrap();
}

fn load_json(root: &Path, rel: &str) -> serde_json::Value {
    let path = root.join(rel);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("bad JSON in {}: {e}", path.display()))
}

fn merge_json_files(root: &Path, files: &[&str]) -> serde_json::Value {
    let mut merged = serde_json::Map::new();
    for f in files {
        if let serde_json::Value::Object(m) = load_json(root, f) {
            merged.extend(m);
        }
    }
    serde_json::Value::Object(merged)
}

fn slim_mons(val: serde_json::Value) -> serde_json::Value {
    let heavy = ["learnset", "events", "evos", "prevo", "evolution_data",
                 "formes", "cosmetic_formes", "base_forme", "changes_from",
                 "gigantamax_move", "required_moves", "required_items"];
    map_object_values(val, |mut obj| {
        for key in &heavy {
            obj.remove(*key);
        }
        obj
    })
}

fn slim_moves(val: serde_json::Value) -> serde_json::Value {
    map_object_values(val, |mut obj| {
        obj.remove("effect");
        obj.remove("condition");
        obj
    })
}

fn map_object_values(
    val: serde_json::Value,
    f: impl Fn(serde_json::Map<String, serde_json::Value>) -> serde_json::Map<String, serde_json::Value>,
) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => {
            let out = map
                .into_iter()
                .map(|(k, v)| {
                    let slimmed = match v {
                        serde_json::Value::Object(inner) => serde_json::Value::Object(f(inner)),
                        other => other,
                    };
                    (k, slimmed)
                })
                .collect();
            serde_json::Value::Object(out)
        }
        other => other,
    }
}

fn emit_kv_table(out: &mut String, name: &str, val: &serde_json::Value) {
    let map: BTreeMap<&str, &serde_json::Value> = match val {
        serde_json::Value::Object(m) => m.iter().map(|(k, v)| (k.as_str(), v)).collect(),
        _ => {
            let compact = serde_json::to_string(val).unwrap();
            out.push_str(&format!(
                "pub static {name}: &[(&str, &str)] = &[\n    (\"\", {raw}),\n];\n\n",
                raw = escaped_raw_str(&compact),
            ));
            return;
        }
    };

    out.push_str(&format!("pub static {name}: &[(&str, &str)] = &[\n"));
    for (k, v) in &map {
        let compact = serde_json::to_string(v).unwrap();
        out.push_str(&format!(
            "    ({key}, {val}),\n",
            key = escaped_raw_str(k),
            val = escaped_raw_str(&compact),
        ));
    }
    out.push_str("];\n\n");
}

fn escaped_raw_str(s: &str) -> String {
    let mut hashes = 0usize;
    loop {
        let delim = "#".repeat(hashes);
        if !s.contains(&format!("\"{})", delim)) && !s.contains(&format!("\"{}", delim)) {
            return format!("r{delim}\"{s}\"{delim}");
        }
        hashes += 1;
    }
}
